language: node_js
node_js:
- stable
deploy:
  provider: heroku
  api_key:
    secure: 
      put: Q2wFUQnS1c4/MXjN1GkhIN5JsBqHRvBl9wGsYDOd06gbqXrlUG08XrZ65kWpmdMwEewatySUmXsF3lVWINsdkrygNc+VH9sk9/EQK8BiTZMmkaRYNfgVznyKtQzQaMtKNH3/hI++Om+7eEghNGPwfOOnzxF3OnJOWSzBpzZkHyiNMsaC9ezKfwxUvXMFL2JQ/fjJYzeoqm92rCoplpb9oZ1qz3FBsTBT794NXHNIbdqW4lBqMtfT0cn83dmBVlO3S2m0aToiRWDFci8a8NG8pKdnYbtfi+Y/3As/idUfhfcb/Tz2Ajki76jQzm0gNBiC1BWqkWjSoHRS/q2cs8Z15oV2PwKHptPJ5Be1ojHL8CgAbCuY5Og3ftVCMWOLAU86UlJ4mdiBPw1e4Xu8u+YDpWSJd6PjeCswY/KlZf1IArefvsr7LOc8TOn8oLwPffqG0f8ry+3tYtA5u+bxMdg5u++RKcTeeJNwe0mJnsnE0/TyUMUVvw9v7O6SiBBFfgAslzQK8NLxkGMIKybbzqXq9Nbu8AWnrtt1hxbYtcbBx6WYvOPZ6i/gJunZMGT+ngazuOXSSr+dZKBkhSMItAxknXOYiz7AHyfl9v6BSv7xr5A4bZcWX0D9HCBQsg95AZrFajM5Vgy0B2xXdG3XmnBTXcyIyTPn9u1VxLrBPHmVbVA=
  app: 
    name: limitless-cove-15146
  on:
    repo: sshaili/Travis-github-heroku